#!/usr/bin/env python3
import sys
from jtag2232 import JTAG2232 
from binascii import hexlify
import decimal


commands = [
'ENDDR',	    # Specifies default end state for DR scan operations.
'ENDIR',	    # Specifies default end state for IR scan operations.
'FREQUENCY',	# Specifies maximum test clock frequency for IEEE 1149.1 bus operations.
'HDR',	      # (Header Data Register) Specifies a header pattern that is prepended to the beginning of subsequent DR scan operations.
'HIR',	      # (Header Instruction Register) Specifies a header pattern that is prepended to the beginning of subsequent IR scan operations.
'PIO',	      # (Parallel Input/Output) Specifies a parallel test pattern.
'PIOMAP', 	  # (Parallel Input/Output Map) Maps PIO column positions to a logical pin.
'RUNTEST',	  # Forces the IEEE 1149.1 bus to a run state for a specified number of clocks or a specified time period.
'SDR',	      # (Scan Data Register) Performs an IEEE 1149.1 Data Register scan.
'SIR',	      # (Scan Instruction Register) Performs an IEEE 1149.1 Instruction Register scan.
'STATE',	    # Forces the IEEE 1149.1 bus to a specified stable state.
'TDR',        # (Trailer Data Register) Specifies a trailer pattern that is appended to the end of subsequent DR scan operations.
'TIR',        # (Trailer Instruction Register) Specifies a trailer pattern that is appended to the end of subsequent IR scan operations.
'TRST'  	    # (Test ReSeT) Controls the optional Test Reset line.
]

jtagstates = [
'RESET',      # stable (with TMS high); acts as if TRST were pulsed
'RUN', 'IDLE',   # stable; don’t assume this always means IDLE
'DRSELECT', 
'DRCAPTURE', 
'DRSHIFT',    # stable; TDI/TDO shifting through the data register
'DREXIT1', 
'DRPAUSE',    # stable; data register ready for update or more shifting
'DREXIT2', 
'DRUPDATE', 
'IRSELECT', 
'IRCAPTURE', 
'IRSHIFT',    # stable; TDI/TDO shifting through the instruction register
'IREXIT1', 
'IRPAUSE',    # stable; instruction register ready for update or more shifting
'IREXIT2', 
'IRUPDATE', 
]

# Utilities
class SVFParseError(Exception):
  def __init__(self, linenumber, msg):
    super().__init__('Line ' + str(linenumber) + ': ' + msg)

class SVFExecError(Exception):
  def __init__(self, linenumber, msg):
    super().__init__('Line ' + str(linenumber) + ': ' + msg)

def hex_to_val(s, *, linenumber):
  try:
    return bytearray.fromhex(s.lstrip('(').rstrip(')'))
  except:
    raise SVFParseError(linenumber, 'Invalid hex literal')

def check_arg_count(min, max, parts, *, linenumber, operation=None):
  op = operation or parts[0]
  if min is not None and len(parts) < min:
    raise SVFParseError(i, '%s operation expects no less than %d arguments' % (op, i))
  elif max is not None and len(parts) > max:
    raise SVFParseError(i, '%s operation expects no more than %d arguments' % (op, i))
    

def equals_with_mask(val, truth, mask, *, masktype, linenumber):
  if not masktype in ['MASK', 'SMASK']: raise SVFParseError(linenumber, 'Invalid mask type')
  if not len(truth) == len(mask): raise SVFParseError(linenumber, 'Mask should match length of expected value')
  if not len(truth) == len(val): raise SVFExecError(linenumber, 'Scan does not match length of expected value')
  for v, t, m in zip(val, truth, mask):
    if (masktype == 'MASK' and v & m != t & m) or (masktype == 'SMASK' and v | m != t | m):
      return False
  return True

# State
interactive = False
strict = True
jtag = JTAG2232('ftdi://0x403:0x6010/1')

PAUSE_DEBUG = len(sys.argv) > 2 and '-p' in sys.argv

if PAUSE_DEBUG:
  print('Enabled pausing for logic debug. Tag !!PAUSE in SVF comment')

# Open input file or interpret from stdin
try:
  if len(sys.argv) > 1:
    src = open(sys.argv[-1])
  else:
    src = sys.stdin
    interactive = True
except:
  print('Failed to open input file')
  raise

long_send = False
long_send_command = None
long_send_index = None
long_send_data = None

for i, line in enumerate(src, 1):
  if interactive and line.strip() == 'nostrict':
    strict = False
    continue
  try:
    len_code = len(line)
    exc = line.find('!')
    dsl = line.find('//')
    if exc >= 0 or dsl >= 0:
      len_code = min(exc, dsl) + 1
      if PAUSE_DEBUG and '!!PAUSE' in line[len_code:]:
        jtag._sync()
        input('Pausing on line ' + str(i) + ': ' + line[len_code:]) 
    parts = line[:len_code].strip().upper().split()
    if len(parts) == 0:
      continue

    if parts[-1] == ';':
      parts.pop(-1)
      long_send = False
    elif parts[-1][-1] == ';':
      parts[-1] = parts[-1].rstrip(';')
      long_send = False
    elif not strict:
      long_send = False
    elif line.count('(') > line.count(')'):
      long_send = True
    elif long_send:
      pass
    else:
      raise SVFParseError(i, 'Missing ;')

    command = long_send_command or parts[0]
    if long_send:
      long_send_command = command

    if command not in commands:
      raise SVFParseError(i, 'Invalid command "' + parts[0] + '"')
    
    # cases for each operation
    if command == 'STATE':
      check_arg_count(2, 2, parts, linenumber=i)
      if parts[1] == 'RESET':
        jtag.reset()
      elif parts[1] == 'IDLE':
        jtag.idle()
      else:
        raise SVFParseError(i, 'STATE "' + parts[1] + '" not supported')

    elif command == 'TRST':
      check_arg_count(2, 3, parts, linenumber=i)
      if parts[1] != 'OFF':
        raise SVFParseError(i, 'TRST not supported')

    elif command in ['HDR', 'HIR', 'TDR', 'TIR']:
      check_arg_count(2, 6, parts, linenumber=i)
      if interactive and parts[1] == '?':
        print(jtag[parts[0]])
      if int(parts[1]) == 0:
        jtag[parts[0]] = (0, bytearray())
      else:
        check_arg_count(4, None, parts, linenumber=i)
        if parts[2] != 'TDI': raise SVFParseError(i, 'Expect TDI label on arg') 
        bitcount = int(parts[1])
        data = hex_to_val(parts[3], linenumber=i)
        jtag[parts[0]] = (bitcount, data)
    
    elif command in ['SDR', 'SIR']:
      if not long_send and long_send_index is None: # not continuing from prior send
        check_arg_count(4, 8, parts, linenumber=i)
        if parts[2] != 'TDI': raise SVFParseError(i, 'Expect TDI label on arg') 
        capture = len(parts) > 4
        bitcount = int(parts[1])
        data = hex_to_val(parts[3], linenumber=i)
        captured = jtag.scan_reg(command[1:], (bitcount, data[::-1]), capture=capture)

        if len(parts) >= 6:
          if parts[4] != 'TDO': raise SVFParseError(i, 'Expect TDO label on arg') 
          expected = hex_to_val(parts[5], linenumber=i)
          maskt = parts[6] if len(parts) >= 8 else 'SMASK'
          mask = hex_to_val(parts[7], linenumber=i) if len(parts) >= 8 else bytearray(len(expected))
          if not equals_with_mask(captured, expected, mask, masktype=maskt, linenumber=i):
            raise SVFExecError(i, 'Value captured differs from expected')
          
      elif long_send and long_send_index is None:
        bitcount = int(parts[1])
        long_send_data_len = bitcount
        if bitcount % 8 != 0:
          raise NotImplementedError('Non-byte long sends not implemented')
        long_send_data = hex_to_val(parts[3], linenumber=i)
        long_send_index = 5
      elif long_send and long_send_index == 5:
        long_send_data.extend(hex_to_val(parts[0], linenumber=i))
      elif not long_send and long_send_index == 5:
        long_send_data.extend(hex_to_val(parts[0], linenumber=i))
        if not len(long_send_data) * 8 == long_send_data_len:
          raise SVFParseError(i, 'Value length differs from expected')
        jtag.scan_reg(command[1:], long_send_data[::-1], capture=False)
        long_send_index = None
        long_send_data = None
        long_send_data_len = None
        long_send_command = None 
      else:
        raise NotImplementedError('Long parse not implemented')

    elif command == 'FREQUENCY':
      check_arg_count(3, 3, parts, linenumber=i)
      if parts[2] == 'HZ':
        hz = int(decimal.Decimal(parts[1]))
      else:
        raise NotImplementedError('Unit for frequency not implemented')
      jtag.set_freq(hz)

    elif command == 'RUNTEST':
      check_arg_count(3, 3, parts, linenumber=i)
      if parts[2] == 'TCK':
        clks = int(parts[1])
      elif parts[2] == 'SEC':
        secs = decimal.Decimal(parts[1])
        clks = int(secs * jtag.freq)
      else:
        raise NotImplementedError('Unit for runtest not implemented')
      jtag.runtest(clks)

  except Exception as e:
    print(e)
    if not interactive:
      raise

jtag._sync()
